### ISSUE TITLE
Sharing iP code quality feedback [for @jq1836]

### ISSUE THREAD

**Issue by soc-se-bot-blue** [jq1836/ip#12]
@jq1836 We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

No easy-to-detect issues :+1: 

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

No easy-to-detect issues :+1: 

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/duke/chatbot/storage/Storage.java` lines `88-94`](https://github.com/jq1836/ip/blob/f444ff74faa74708451f037339a5b862d64845b9/src/main/java/duke/chatbot/storage/Storage.java#L88..L94):

```java

    /**
     * Return list of tasks after loading them from the stored file.
     *
     * @return A list of tasks loaded from the stored file.
     * @throws FileNotFoundException If a file is not found.
     * @throws InvalidInputException If the date and time portion of the encoded task is not in the correct format.
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message (Subject Only)

No easy-to-detect issues :+1: 

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by jq1836** [comment]
Updated code with feedback in mind.
